<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-PTF1H2O" failures="1" tests="1" name="Default test" time="57.949" errors="0" timestamp="2023-12-15T17:52:54 IST">
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="HPAOtherDeploymentInfo" time="45.258">
    <failure type="java.lang.AssertionError" message="expected [perfeasy-testing] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [perfeasy-testing] but found [1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.buildpiper.pages.ServiceCreationPage.VerifyHPAMonitoring(ServiceCreationPage.java:1562)
at com.buildpiper.testcases.ServiceCreationTestcases.HPAOtherDeploymentInfo(ServiceCreationTestcases.java:172)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- HPAOtherDeploymentInfo -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="CreateSesrviceNegativeTest1" time="0.0">
    <ignored/>
  </testcase> <!-- CreateSesrviceNegativeTest1 -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="createHelmService" time="0.0">
    <ignored/>
  </testcase> <!-- createHelmService -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="ServiceOverviewSearch" time="0.0">
    <ignored/>
  </testcase> <!-- ServiceOverviewSearch -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="createServ" time="0.0">
    <ignored/>
  </testcase> <!-- createServ -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="BuildDeployAlternate" time="0.0">
    <ignored/>
  </testcase> <!-- BuildDeployAlternate -->
  <testcase classname="com.buildpiper.testcases.ServiceCreationTestcases" name="CreateBuildXService" time="0.0">
    <ignored/>
  </testcase> <!-- CreateBuildXService -->
</testsuite> <!-- Default test -->
